const subheadings = {
    "techConference": [
      "The Break Room: Innovations That Redefine Work",
      "Refining Protocols: AI and Automation at Work",
      "The Overtime Contingency: Tech That Never Sleeps",
      "Mind, Machine, and Memory: The Future of Human-AI Integration",
      "The Wellness Check: Ethics in Emerging Technology",
      "Eagan’s Vision: The Future of Corporate Tech",
      "The Code Detector: Identifying Hidden Patterns in Big Data",
      "The Compartmentalized Mind: Exploring Tech and Neurohacking",
      "Bridging the Severance Barrier: The Role of Consciousness in AI",
      "Tech Lumon Would Approve: The New Age of Digital Workflows",
      "Automated Boundaries: The Rise of AI in the Workplace",
      "Building the Future, One Line of Code at a Time",
      "Severing the Connection: How Work Culture is Evolving",
      "Tech in the New Age of Severed Minds",
      "Data & Control: Navigating the Ethics of Corporate Tech",
      "Understanding the Human Condition Through Technology",
      "In the Minds of the Engineers: Creating Future Workspaces",
      "Mastering the Art of Workflow Design in a Tech-Driven World",
      "Tech, Ethics, and the Corporate Labyrinth"
    ],
    "techWebinar": [
      "Orientation: A Deep Dive into the Next Era of Tech",
      "Severing Distractions: The Art of Focus in the Digital Age",
      "Perks & Incentives: Navigating Tech Benefits and Career Growth",
      "The Boardroom Sees All: Data Privacy and Surveillance in Tech",
      "Waffle Parties & Workplace Culture: Building Strong Tech Teams",
      "The Finger Trap Exercise: Gamifying Productivity in the Workplace",
      "Meet Your Outie: The Importance of Digital Identity and Security",
      "Numbers as a Feeling: The Psychology Behind UX and AI",
      "Helly R’s Guide to Breaking Into Tech",
      "The Kier Philosophy: Balancing Innovation and Ethics",
      "The Good Place: Building a Positive Digital Work Environment",
      "Severing the Traditional Tech Hierarchy: Decentralizing Leadership",
      "Uncovering Your Tech Persona: What’s Your Role in Innovation?",
      "Tech Mindfulness: How to Survive in a 24/7 Digital World",
      "Code of Ethics: Aligning Your Career with Tech’s Moral Compass",
      "From Paper to Pixels: How Tech is Changing the Workforce",
      "Breaking the Box: Tech Innovation in Unexpected Places",
      "The Path to Digital Enlightenment: How to Break Into Tech",
      "Maximizing Your Digital Identity and Personal Branding"
    ],
    "hackathonJobFair": [
      "Join the Lumon Family: Finding Your Purpose in Tech",
      "The Path to Kier: Leadership and Growth in Tech Careers",
      "Which Department Are You? Matching Skills to Roles",
      "No Outies Allowed: Thriving in Remote and Hybrid Work",
      "Your Card is Green: Breaking into the Tech Industry",
      "The Macrodata Refinement Challenge: Cleaning and Structuring Data",
      "Defying the Code Detectors: Breaking Barriers in Cybersecurity",
      "Building the Elevator: Advancing Interconnectivity and APIs",
      "Hacking the Severance Barrier: Exploring Ethical AI",
      "The Great Escape: Innovating Work-Life Balance in the Tech World",
      "The Escape Room Challenge: Solving Real-World Tech Problems",
      "Unlocking Your Potential: Tech Career Opportunities Await",
      "Code for the Future: How Hackathons Are Shaping Tomorrow",
      "The Outie to Innie Transformation: Finding Your Place in Tech",
      "Elevator Pitch: Presenting Your Career to Potential Employers",
      "Techie’s Toolbox: What You Need to Stand Out in a Hackathon",
      "Building the Perfect Team: Collaborating for Success",
      "The Liminal Space: Exploring New Career Paths in Tech",
      "Beyond the Code: Career Growth and Development in Tech"
    ]
  }



const flattened = [
  "The Break Room: Innovations That Redefine Work",
  "Refining Protocols: AI and Automation at Work",
  "The Overtime Contingency: Tech That Never Sleeps",
  "Mind, Machine, and Memory: The Future of Human-AI Integration",
  "The Wellness Check: Ethics in Emerging Technology",
  "Eagan’s Vision: The Future of Corporate Tech",
  "The Code Detector: Identifying Hidden Patterns in Big Data",
  "The Compartmentalized Mind: Exploring Tech and Neurohacking",
  "Bridging the Severance Barrier: The Role of Consciousness in AI",
  "Tech Lumon Would Approve: The New Age of Digital Workflows",
  "Automated Boundaries: The Rise of AI in the Workplace",
  "Building the Future, One Line of Code at a Time",
  "Severing the Connection: How Work Culture is Evolving",
  "Tech in the New Age of Severed Minds",
  "Data & Control: Navigating the Ethics of Corporate Tech",
  "Understanding the Human Condition Through Technology",
  "In the Minds of the Engineers: Creating Future Workspaces",
  "Mastering the Art of Workflow Design in a Tech-Driven World",
  "Tech, Ethics, and the Corporate Labyrinth",
  "Orientation: A Deep Dive into the Next Era of Tech",
  "Severing Distractions: The Art of Focus in the Digital Age",
  "Perks & Incentives: Navigating Tech Benefits and Career Growth",
  "The Boardroom Sees All: Data Privacy and Surveillance in Tech",
  "Waffle Parties & Workplace Culture: Building Strong Tech Teams",
  "The Finger Trap Exercise: Gamifying Productivity in the Workplace",
  "Meet Your Outie: The Importance of Digital Identity and Security",
  "Numbers as a Feeling: The Psychology Behind UX and AI",
  "Helly R’s Guide to Breaking Into Tech",
  "The Kier Philosophy: Balancing Innovation and Ethics",
  "The Good Place: Building a Positive Digital Work Environment",
  "Severing the Traditional Tech Hierarchy: Decentralizing Leadership",
  "Uncovering Your Tech Persona: What’s Your Role in Innovation?",
  "Tech Mindfulness: How to Survive in a 24/7 Digital World",
  "Code of Ethics: Aligning Your Career with Tech’s Moral Compass",
  "From Paper to Pixels: How Tech is Changing the Workforce",
  "Breaking the Box: Tech Innovation in Unexpected Places",
  "The Path to Digital Enlightenment: How to Break Into Tech",
  "Maximizing Your Digital Identity and Personal Branding",
  "Join the Lumon Family: Finding Your Purpose in Tech",
  "The Path to Kier: Leadership and Growth in Tech Careers",
  "Which Department Are You? Matching Skills to Roles",
  "No Outies Allowed: Thriving in Remote and Hybrid Work",
  "Your Card is Green: Breaking into the Tech Industry",
  "The Macrodata Refinement Challenge: Cleaning and Structuring Data",
  "Defying the Code Detectors: Breaking Barriers in Cybersecurity",
  "Building the Elevator: Advancing Interconnectivity and APIs",
  "Hacking the Severance Barrier: Exploring Ethical AI",
  "The Great Escape: Innovating Work-Life Balance in the Tech World",
  "The Escape Room Challenge: Solving Real-World Tech Problems",
  "Unlocking Your Potential: Tech Career Opportunities Await",
  "Code for the Future: How Hackathons Are Shaping Tomorrow",
  "The Outie to Innie Transformation: Finding Your Place in Tech",
  "Elevator Pitch: Presenting Your Career to Potential Employers",
  "Techie’s Toolbox: What You Need to Stand Out in a Hackathon",
  "Building the Perfect Team: Collaborating for Success",
  "The Liminal Space: Exploring New Career Paths in Tech",
  "Beyond the Code: Career Growth and Development in Tech"
];


  export default {
    subheadings,
    flattened
  };